# Generated by Django 4.1.2 on 2022-10-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('describe', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('describe', models.CharField(default='', max_length=500)),
                ('status', models.CharField(choices=[('TD', 'Todo'), ('DI', 'Doing'), ('DN', 'Done'), ('AD', 'Abandon')], default='TD', max_length=2)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
            ],
        ),
    ]
